version: '3'
services:
  sse_nginx:
    build: . 
    container_name: sse_nginx
    ports:
      - 80:80
    depends_on:
      - "sse_web"
      - "sse_api"
    networks:
      - sse-network
      
  sse_web: 
    build: ./web
    container_name: sse_web
    expose:
      - 80
    networks:
      - sse-network

  sse_api:
    build: ./api
    container_name: sse_api
    command: sh -c "node index.js"
    expose:
      - 3000
    networks:
      - sse-network

networks:
  sse-network:
    external:
      name: sse-network